### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by tarcieri** [seb-m/common.rs#1]
This is a cool looking library, but "common" is a terrible name

**Comment by seb-m** [comment]
Agreed! This is really a bad name, originally I didn't search a more descriptive name in part because I'm not sure of the scope of the code in this repo. Currently I reexport its main modules with this other project [crypto.rs](https://github.com/seb-m/crypto.rs).

**Comment by tarcieri** [comment]
I think it'd be awesome to at least share the `SBuf` stuff across multiple Rust crypto projects. I was actually working on a project (rust-secretbuffer) to do exactly the same stuff before I noticed yours in a better state of completion :wink:

**Comment by seb-m** [comment]
I've moved and rewritten the allocation part of this project [here](https://github.com/seb-m/tars), with [better allocations](http://seb.dbzteam.org/rs/tars/tars/malloc/index.html) and [RAII stuff](http://seb.dbzteam.org/rs/tars/tars/struct.ProtKey.html). Not sure it is dramatically a better name though ;)

**Comment by tarcieri** [comment]
If that's an Interstellar reference I approve :wink:

**Comment by seb-m** [comment]
I couldn't resist indeed, a badass robot with his name ending with "rs" :)
